#!/bin/sh

username=''
password=''
domain=''

# ensure we have curl
which curl > /dev/null 2>&1
if [ 0 -ne $? ];
then
   echo "$0: failed: can't find curl"
   exit 1
fi

# get our external ip
ip=`curl -s ipinfo.io/ip`
if [ 0 -ne $? ];
then
   echo "$0: failed: can't get ip"
   exit 2
fi

# update google domains ddns
gdns="domains.google.com/nic/update"
url="https://${username}:${password}@${gdns}?hostname=${domain}&myip=${ip}"
response=`curl -s $url | awk '{print $1}'`

# parse response
if [ 0 -ne $? ];
then
   echo "$0: failed: can't update google dynamic dns"
   exit 3
elif [ "good" == "${response}" ];
then
   echo "$0: succeeded: ip successfully changed to ${ip}"
   exit 0
elif [ "nochg" == "${response}" ];
then
   echo "$0: succeeded: no change in currently registered ip address"
   exit 0
else
   echo "$0: failed: unknown error: output from google: '${response}'"
   exit 4
fi

# this shouldn't be reached
echo "$0: failed: somewhere, something when horribly wrong"
exit 5
